### ISSUE TITLE
Used Path variable

### ISSUE THREAD

**Issue by StefAlb** [anb0s/EasyShell#159] opened 2018-01-09 07:50 UTC
**Used Path variable**

If I open a windows command shell via easyshell, the shell does not use the configured system "Path" environment variable ... in opposite if I open a command shell outside eclipse.

What can I do to change this?

- Plugin version: 2.1.0.v20170508-1844
- Eclipse Version: Oxygen.2 Release (4.7.2) Build id: 20171218-0600
- Java Version: jdk1.8.0_151
- Operating System Version: Windows10

**Comment by anb0s** [comment] 2018-01-11 11:46
I'm sure it must work, because i'm using it daily. Please call in your opened command shell:
`echo %PATH%`
and check if it shows same pathes from your system "Path" environment variable.

**Comment by StefAlb** [comment] 2018-01-11 12:55
I  had done this and I would also expect that it's works ... I had never this problem in the past until last week and I use easyshell since years. At the moment I assume that this is an OS  or eclipse problem.

However the problem disappears yesterday and I had it again today. But after a restart of eclipse the problem had gone again. So I hope this was a local issue on my PC.

**Comment by anb0s** [comment] 2018-01-11 13:56
Thanks for the feedback! I've looked in the code and see that i'm using "ProcessBuilder" here and do not touch the environment (commented out). As expected from [description](https://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html) it just passes the environment from Eclipse process (initial value), so Path etc. should be good:

> an environment, which is a system-dependent mapping from variables to values. The initial value is a copy of the environment of the current process (see System.getenv()).

I think it can be OS, Eclipse process or Java process... hm...

Code:
```
    	// get working directory
    	File workingDirectory = getWorkingDirectoryResolved(variableManager);
        // get command    	
        String[] command = getCommandResolved(variableManager);
        // create process builder with command and ...
        ProcessBuilder pb = new ProcessBuilder(command);
        // ... set working directory and redirect error stream
        if (workingDirectory != null) {
            pb.directory(workingDirectory);
        }
        Activator.logDebug("exc:<---");
        // get passed system environment
        //Map<String, String> env = pb.environment();
        // add own variables
        pb.start();

```

**Comment by anb0s** [comment] 2018-03-01 19:40
Close this one, because it looks like OS or Eclipse issue. Please reopen if it's still reproducible. Thanks!

**Closed by anb0s** 2018-03-01 19:40 UTC
Labels: OS - Windows, Other plugin bug or not compatible, Version 2.1.x, investigation
